[package]
name = "postgres_array"
version = "0.1.2"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Array support for rust-postgres"
repository = "https://github.com/sfackler/rust-postgres-array"

[features]
default = ["uuid"]

[dependencies]
postgres = "0.5"
rustc-serialize = "0.2"
time = "0.1"

[dependencies.uuid]
optional = true
version = "0.1"
